apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-uenc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-uenc
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: devfile-sample-go-basic-uenc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-uenc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-uenc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-sabiswas-tenant/devfile-sample-go-basic/devfile-sample-go-basic-uenc@sha256:d6cede7bfb0442a289c6a433bb84379f7ee40d5a2f5667a6002896c802199171
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
